### ISSUE TITLE
Negative numbers + isdigit()

### ISSUE THREAD

**Issue by mchlltt** [elliewix/data-profile-tool#3]
I think I fixed this the other day, but I need to test and commit, so I wanted to make an issue to be sure it doesn't slip through the cracks :)

I have some variables with negative values, which throws `review_csv` off. Negative numbers pass `try: float(x)`, but `isdigit()` determines what is actually factored into `digit_values`. Because of the '-', negative numbers return `False` for `isdigit()`. The bit of code that determines `digit_values` just needs tweaked.

**Comment by elliewix** [comment]
Whoops, forgot that I used that twice!  I just committed a change where items that pass float(d) are now collected as a list, which is reused in place of digit_values.  Give that a try now.

**Comment by mchlltt** [comment]
Hmm. I tried again and got the same error. To be more clear, I think this line in particular is giving me problems:

https://github.com/elliewix/data-profile-tool/blob/master/data_profile.py#L84

**Comment by mchlltt** [comment]
Actually, I think maybe you just didn't push that particular commit?

**Comment by elliewix** [comment]
//headdesk// pushing now
